# Generated by Django 2.2.7 on 2020-03-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('image', models.FileField(upload_to='Category/')),
            ],
        ),
    ]
